/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.DecimalFormat;
import java.util.Calendar;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author schmidtu
 */
public class BDE_MainFrame extends javax.swing.JFrame {
    
    public boolean EndingMyThread = false;
    DefaultTableModel myTableModel;

    /**
     * Creates new form BDE_MainFrame
     */
    public BDE_MainFrame() {
        initComponents();
        this.do_startTheClock();
        this.do_manageAllBeforeShow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_head_buttons = new javax.swing.JPanel();
        btn_employee_signOn = new javax.swing.JButton();
        btn_employee_signOff = new javax.swing.JButton();
        btn_order_signOn = new javax.swing.JButton();
        btn_order_signOff = new javax.swing.JButton();
        btn_activities = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jPanel_clock = new javax.swing.JPanel();
        lbl_clock = new javax.swing.JLabel();
        lbl_currentDate = new javax.swing.JLabel();
        jPanel_workArea = new javax.swing.JPanel();
        jComboBox_workArea = new javax.swing.JComboBox<>();
        jPanel_team = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_employeesSignedOn = new javax.swing.JTable();
        jPanel_currentJobs = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_currentJobs = new javax.swing.JTable();
        jPanel_currentArticleData = new javax.swing.JPanel();
        jTextField_currentOrder = new javax.swing.JTextField();
        lbl_currentOrder = new javax.swing.JLabel();
        lbl_currentArticle = new javax.swing.JLabel();
        jTextFieldl_currentArticle = new javax.swing.JTextField();
        lbl_currentArticleCountOfUse = new javax.swing.JLabel();
        jTextField_currentArticleCountOfUse = new javax.swing.JTextField();
        lbl_plannedStartInProduction = new javax.swing.JLabel();
        jTextFiell_plannedStartInProduction = new javax.swing.JTextField();
        lbl_currentMachine = new javax.swing.JLabel();
        jTextField_currentMachine = new javax.swing.JTextField();
        jPanel_currentJob = new javax.swing.JPanel();
        btn_currentJob_start = new javax.swing.JButton();
        btn_currentJob_end = new javax.swing.JButton();
        jTextFieldlbl_currentJob_startTime = new javax.swing.JTextField();
        lbl_currentJob_startTime = new javax.swing.JLabel();
        lbl_currentJob_endTime = new javax.swing.JLabel();
        jTextFieldlbl_currentJob_endTime = new javax.swing.JTextField();
        jTextField_remarks_fromOutside = new javax.swing.JTextField();
        jTextField_remarks_toOutside = new javax.swing.JTextField();
        lbl_remarks_fromOutside = new javax.swing.JLabel();
        lbl_remarks_toOutside = new javax.swing.JLabel();
        jPanel_currentTool_components = new javax.swing.JPanel();
        lbl_currentWKZ = new javax.swing.JLabel();
        jTextFiell_currentTool = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_employee_signOn.setText("<html>Personal<br>anmelden</html>");
        btn_employee_signOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employee_signOnActionPerformed(evt);
            }
        });

        btn_employee_signOff.setText("<html>Personal<br>abmelden</html>");

        btn_order_signOn.setText("<html>Auftrag<br>anmelden</html>");
        btn_order_signOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_order_signOnActionPerformed(evt);
            }
        });

        btn_order_signOff.setText("<html>Auftrag<br>abmelden</html>");

        btn_activities.setText("Tätigkeit");

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_head_buttonsLayout = new javax.swing.GroupLayout(jPanel_head_buttons);
        jPanel_head_buttons.setLayout(jPanel_head_buttonsLayout);
        jPanel_head_buttonsLayout.setHorizontalGroup(
            jPanel_head_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_head_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_employee_signOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_employee_signOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order_signOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_order_signOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(btn_activities)
                .addGap(30, 30, 30)
                .addComponent(btn_exit)
                .addContainerGap())
        );
        jPanel_head_buttonsLayout.setVerticalGroup(
            jPanel_head_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_head_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_head_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_employee_signOn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_employee_signOff, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_order_signOn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_activities, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_order_signOff, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbl_clock.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbl_clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_clock.setText("jLabel1");

        lbl_currentDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_currentDate.setText("jLabel7");

        javax.swing.GroupLayout jPanel_clockLayout = new javax.swing.GroupLayout(jPanel_clock);
        jPanel_clock.setLayout(jPanel_clockLayout);
        jPanel_clockLayout.setHorizontalGroup(
            jPanel_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_clock, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(lbl_currentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_clockLayout.setVerticalGroup(
            jPanel_clockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_clock, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_currentDate))
        );

        jComboBox_workArea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel_workAreaLayout = new javax.swing.GroupLayout(jPanel_workArea);
        jPanel_workArea.setLayout(jPanel_workAreaLayout);
        jPanel_workAreaLayout.setHorizontalGroup(
            jPanel_workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_workArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_workAreaLayout.setVerticalGroup(
            jPanel_workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_workAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox_workArea, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable_employeesSignedOn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Vorname"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_employeesSignedOn);

        javax.swing.GroupLayout jPanel_teamLayout = new javax.swing.GroupLayout(jPanel_team);
        jPanel_team.setLayout(jPanel_teamLayout);
        jPanel_teamLayout.setHorizontalGroup(
            jPanel_teamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_teamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_teamLayout.setVerticalGroup(
            jPanel_teamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_teamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable_currentJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bereich", "Artikel", "Start"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_currentJobs);

        javax.swing.GroupLayout jPanel_currentJobsLayout = new javax.swing.GroupLayout(jPanel_currentJobs);
        jPanel_currentJobs.setLayout(jPanel_currentJobsLayout);
        jPanel_currentJobsLayout.setHorizontalGroup(
            jPanel_currentJobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_currentJobsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_currentJobsLayout.setVerticalGroup(
            jPanel_currentJobsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_currentJobsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextField_currentOrder.setEditable(false);

        lbl_currentOrder.setText("Fertigungsauftrag");

        lbl_currentArticle.setText("Artikel");

        jTextFieldl_currentArticle.setEditable(false);

        lbl_currentArticleCountOfUse.setText("Nutzen");

        jTextField_currentArticleCountOfUse.setEditable(false);

        lbl_plannedStartInProduction.setText("geplanter Start in der Produktion");

        jTextFiell_plannedStartInProduction.setEditable(false);

        lbl_currentMachine.setText("Maschine");

        jTextField_currentMachine.setEditable(false);

        javax.swing.GroupLayout jPanel_currentArticleDataLayout = new javax.swing.GroupLayout(jPanel_currentArticleData);
        jPanel_currentArticleData.setLayout(jPanel_currentArticleDataLayout);
        jPanel_currentArticleDataLayout.setHorizontalGroup(
            jPanel_currentArticleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_currentArticleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_currentArticleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_currentArticleDataLayout.createSequentialGroup()
                        .addComponent(lbl_currentArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_currentOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_currentArticleDataLayout.createSequentialGroup()
                        .addComponent(jTextFieldl_currentArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_currentOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_currentArticleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_currentMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_currentMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_currentArticleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFiell_plannedStartInProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_plannedStartInProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel_currentArticleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_currentArticleCountOfUse, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_currentArticleCountOfUse, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_currentArticleDataLayout.setVerticalGroup(
            jPanel_currentArticleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_currentArticleDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_currentArticleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_currentOrder)
                    .addComponent(lbl_currentArticle)
                    .addComponent(lbl_currentArticleCountOfUse)
                    .addComponent(lbl_plannedStartInProduction)
                    .addComponent(lbl_currentMachine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_currentArticleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_currentOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldl_currentArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_currentArticleCountOfUse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFiell_plannedStartInProduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_currentMachine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_currentJob_start.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn_currentJob_start.setText("Start");

        btn_currentJob_end.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btn_currentJob_end.setText("Stopp");

        jTextFieldlbl_currentJob_startTime.setEditable(false);
        jTextFieldlbl_currentJob_startTime.setText("jTextField1");

        lbl_currentJob_startTime.setText("Start aktueller Arbeitsgang");

        lbl_currentJob_endTime.setText("Ende aktueller Arbeitsgang");

        jTextFieldlbl_currentJob_endTime.setEditable(false);
        jTextFieldlbl_currentJob_endTime.setText("jTextField2");

        jTextField_remarks_fromOutside.setEditable(false);
        jTextField_remarks_fromOutside.setText("jTextField1");

        jTextField_remarks_toOutside.setText("jTextField1");

        lbl_remarks_fromOutside.setText("Bemerkungen für den aktuellen Arbeitsbereich");

        lbl_remarks_toOutside.setText("Bemerkungen zur Weitergabe");

        javax.swing.GroupLayout jPanel_currentJobLayout = new javax.swing.GroupLayout(jPanel_currentJob);
        jPanel_currentJob.setLayout(jPanel_currentJobLayout);
        jPanel_currentJobLayout.setHorizontalGroup(
            jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_currentJobLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_remarks_fromOutside)
                        .addComponent(btn_currentJob_start, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addComponent(lbl_currentJob_startTime)
                        .addComponent(jTextFieldlbl_currentJob_startTime, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_remarks_fromOutside))
                .addGap(18, 18, 18)
                .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_remarks_toOutside)
                    .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_currentJob_endTime)
                        .addComponent(btn_currentJob_end, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                        .addComponent(jTextFieldlbl_currentJob_endTime, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_remarks_toOutside)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_currentJobLayout.setVerticalGroup(
            jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_currentJobLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_currentJob_start, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(btn_currentJob_end, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_currentJob_startTime)
                    .addComponent(lbl_currentJob_endTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldlbl_currentJob_startTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldlbl_currentJob_endTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_remarks_fromOutside)
                    .addComponent(lbl_remarks_toOutside))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_currentJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_remarks_fromOutside, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jTextField_remarks_toOutside))
                .addContainerGap())
        );

        lbl_currentWKZ.setText("WKZ - Werkzeug");

        jTextFiell_currentTool.setEditable(false);
        jTextFiell_currentTool.setText("jTextField1");

        jLabel1.setText("GF - Grundform");

        jTextField1.setText("jTextField1");

        jLabel2.setText("KWV - Vorstempel");

        jTextField2.setText("jTextField2");

        jLabel3.setText("KWS - Schnitt");

        jTextField3.setText("jTextField3");

        jLabel4.setText("KSB - Stanzbrille");

        jTextField4.setText("jTextField4");

        jLabel5.setText("KWR - Stapelung");

        jTextField5.setText("jTextField5");

        jLabel6.setText("KWN - Niederhalter");

        jTextField6.setText("jTextField6");

        javax.swing.GroupLayout jPanel_currentTool_componentsLayout = new javax.swing.GroupLayout(jPanel_currentTool_components);
        jPanel_currentTool_components.setLayout(jPanel_currentTool_componentsLayout);
        jPanel_currentTool_componentsLayout.setHorizontalGroup(
            jPanel_currentTool_componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_currentTool_componentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_currentTool_componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFiell_currentTool)
                    .addComponent(lbl_currentWKZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_currentTool_componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_currentTool_componentsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel_currentTool_componentsLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_currentTool_componentsLayout.setVerticalGroup(
            jPanel_currentTool_componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_currentTool_componentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_currentTool_componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_currentWKZ)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_currentTool_componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_currentTool_componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFiell_currentTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_currentTool_componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_head_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel_team, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_workArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_clock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_currentJobs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_currentArticleData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_currentTool_components, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_currentJob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_head_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_currentArticleData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_clock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_workArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_currentTool_components, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_currentJobs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_currentJob, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_employee_signOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employee_signOnActionPerformed
        // TODO add your handling code here:
        BDE_EmployeeDialog bde_mainDialog = new BDE_EmployeeDialog(this,true, "SIGN_ON");
        bde_mainDialog.setTitle("Personal anmelden");
        bde_mainDialog.setSize(1400, 900);
        bde_mainDialog.setResizable(false);
        bde_mainDialog.setLocation(50, 50);
        bde_mainDialog.setVisible(true);
        String[] currentEmployeeData = bde_mainDialog.getValueAsArray();
        this.setCurrentEmployeeData(currentEmployeeData);
    }//GEN-LAST:event_btn_employee_signOnActionPerformed

    private void btn_order_signOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_order_signOnActionPerformed
        // TODO add your handling code here:
        BDE_OrderDialog bde_orderDialog = new BDE_OrderDialog(this, true, "SIGN_ON");
        bde_orderDialog.setTitle("Auftrag anmelden");
        bde_orderDialog.setSize(1400, 900);
        bde_orderDialog.setResizable(false);
        bde_orderDialog.setLocation(50, 50);
        bde_orderDialog.setVisible(true);
        String[] currentArticleData = bde_orderDialog.getValueAsArray();
        this.setCurrentArticleData(currentArticleData);
    }//GEN-LAST:event_btn_order_signOnActionPerformed

    
    private void setCurrentEmployeeData(String[] anArrayOfValues) {
       myTableModel = (DefaultTableModel) jTable_employeesSignedOn.getModel();
       myTableModel.addRow(anArrayOfValues);
    }
    
    private void setCurrentArticleData(String[] anArrayOfValues) {
        jTextField_currentOrder.setText(anArrayOfValues[0]);
        jTextFieldl_currentArticle.setText(anArrayOfValues[1]);
        jTextField_currentMachine.setText(anArrayOfValues[2]);
        jTextFiell_plannedStartInProduction.setText(anArrayOfValues[3]);
    }
    
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        //        Thread.interrupt();
        //        System.gc();
        EndingMyThread = true;
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    private void do_startTheClock() {
        Thread myThread = new Thread(){
        @Override
        public void run() 
        {
            while(!EndingMyThread) {
                try{ Thread.sleep(50); } catch( Throwable e) { e.printStackTrace(); }
                Calendar cal = Calendar.getInstance();
                DecimalFormat myFormat = new DecimalFormat("00");
                int myHour = cal.get(Calendar.HOUR_OF_DAY);  
                int myMin = cal.get(Calendar.MINUTE);
                int mySec = cal.get(Calendar.SECOND);
                String myTimeNew = myFormat.format(myHour) +":"+ myFormat.format(myMin) +":"+ myFormat.format(mySec);
                lbl_clock.setText(myTimeNew);                
            }
        }
        };        
        myThread.start();
    }    
    
    private void do_manageAllBeforeShow() {
        jPanel_head_buttons.setBorder(BorderFactory.createTitledBorder(" Bearbeitung "));
        jPanel_clock.setBorder(BorderFactory.createTitledBorder(" Aktuelle Uhrzeit "));
        jPanel_workArea.setBorder(BorderFactory.createTitledBorder(" Arbeitsbereich "));
        jComboBox_workArea.addItem("WZV");
        jComboBox_workArea.addItem("Werkstatt");
        jPanel_team.setBorder(BorderFactory.createTitledBorder(" Team "));
        jPanel_currentJobs.setBorder(BorderFactory.createTitledBorder(" Aktuelle Tätigkeiten "));
        jPanel_currentArticleData.setBorder(BorderFactory.createTitledBorder(" Aktueller Artikel / FA "));
        jPanel_currentJob.setBorder(BorderFactory.createTitledBorder(" Aktueller Arbeitsgang "));
        jPanel_currentTool_components.setBorder(BorderFactory.createTitledBorder(" Werkzeugkomponenten "));
        DateTimeFormatter df = DateTimeFormatter.ofPattern("dd.MM.yyy");
        lbl_currentDate.setText(LocalDate.now().format(df));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDE_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDE_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDE_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDE_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BDE_MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_activities;
    private javax.swing.JButton btn_currentJob_end;
    private javax.swing.JButton btn_currentJob_start;
    private javax.swing.JButton btn_employee_signOff;
    private javax.swing.JButton btn_employee_signOn;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_order_signOff;
    private javax.swing.JButton btn_order_signOn;
    private javax.swing.JComboBox<String> jComboBox_workArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel_clock;
    private javax.swing.JPanel jPanel_currentArticleData;
    private javax.swing.JPanel jPanel_currentJob;
    private javax.swing.JPanel jPanel_currentJobs;
    private javax.swing.JPanel jPanel_currentTool_components;
    private javax.swing.JPanel jPanel_head_buttons;
    private javax.swing.JPanel jPanel_team;
    private javax.swing.JPanel jPanel_workArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_currentJobs;
    private javax.swing.JTable jTable_employeesSignedOn;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField_currentArticleCountOfUse;
    private javax.swing.JTextField jTextField_currentMachine;
    private javax.swing.JTextField jTextField_currentOrder;
    private javax.swing.JTextField jTextField_remarks_fromOutside;
    private javax.swing.JTextField jTextField_remarks_toOutside;
    private javax.swing.JTextField jTextFieldl_currentArticle;
    private javax.swing.JTextField jTextFieldlbl_currentJob_endTime;
    private javax.swing.JTextField jTextFieldlbl_currentJob_startTime;
    private javax.swing.JTextField jTextFiell_currentTool;
    private javax.swing.JTextField jTextFiell_plannedStartInProduction;
    private javax.swing.JLabel lbl_clock;
    private javax.swing.JLabel lbl_currentArticle;
    private javax.swing.JLabel lbl_currentArticleCountOfUse;
    private javax.swing.JLabel lbl_currentDate;
    private javax.swing.JLabel lbl_currentJob_endTime;
    private javax.swing.JLabel lbl_currentJob_startTime;
    private javax.swing.JLabel lbl_currentMachine;
    private javax.swing.JLabel lbl_currentOrder;
    private javax.swing.JLabel lbl_currentWKZ;
    private javax.swing.JLabel lbl_plannedStartInProduction;
    private javax.swing.JLabel lbl_remarks_fromOutside;
    private javax.swing.JLabel lbl_remarks_toOutside;
    // End of variables declaration//GEN-END:variables
}
