/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author schmidtu
 */
public class BDE_TaetigkeitenDialog extends javax.swing.JDialog {

    /**
     * Creates new form BDE_TaetigkeitenDialog
     * @param parent
     * @param modal
     */
    public BDE_TaetigkeitenDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    String Taetigkeit;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_base = new javax.swing.JPanel();
        btn_Vorbereitung = new javax.swing.JButton();
        btn_ReparaturSchnittStanzbrille = new javax.swing.JButton();
        btn_Schichtuebergabe = new javax.swing.JButton();
        btn_Nacharbeit = new javax.swing.JButton();
        btn_Schnittebox = new javax.swing.JButton();
        btn_WartenAufAuftrag = new javax.swing.JButton();
        btn_Demontage = new javax.swing.JButton();
        btn_EinAuslagerungWerkzeugKomponente = new javax.swing.JButton();
        btn_WartenAufWerkzeugAusDerProduktion1 = new javax.swing.JButton();
        btn_MontageSTAL = new javax.swing.JButton();
        btn_EinlagerungSchnitt = new javax.swing.JButton();
        btn_BesprechungVersammlung = new javax.swing.JButton();
        btn_DemontageSTAL = new javax.swing.JButton();
        btn_SucheWerkzeugKomponente = new javax.swing.JButton();
        btn_Schulung = new javax.swing.JButton();
        btn_ReparaturFormstation = new javax.swing.JButton();
        btn_PutzenReinigung = new javax.swing.JButton();
        btn_Pause = new javax.swing.JButton();
        btn_ReparaturStapelung = new javax.swing.JButton();
        btn_Segmentwechsel = new javax.swing.JButton();
        btn_KeineMitarbeiter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel_base.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_base.setLayout(new java.awt.GridLayout(7, 3, 20, 10));

        btn_Vorbereitung.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Vorbereitung.setText("<html><center>1. Vorbereitung</center></html>");
        btn_Vorbereitung.setAlignmentY(0.0F);
        btn_Vorbereitung.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_Vorbereitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VorbereitungActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_Vorbereitung);

        btn_ReparaturSchnittStanzbrille.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_ReparaturSchnittStanzbrille.setText("<html><center>12. Reparatur:<br> Schnitt / Stanzbrille</center></html>");
        btn_ReparaturSchnittStanzbrille.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_ReparaturSchnittStanzbrille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReparaturSchnittStanzbrilleActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_ReparaturSchnittStanzbrille);

        btn_Schichtuebergabe.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Schichtuebergabe.setText("<html><center>80. Schichtübergabe</center></html>");
        btn_Schichtuebergabe.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_Schichtuebergabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SchichtuebergabeActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_Schichtuebergabe);

        btn_Nacharbeit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Nacharbeit.setText("<html><center>2. Nacharbeit</center></html>");
        btn_Nacharbeit.setAlignmentY(0.0F);
        btn_Nacharbeit.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_Nacharbeit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NacharbeitActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_Nacharbeit);

        btn_Schnittebox.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Schnittebox.setText("<html><center>40. Schnittebox</center></html>");
        btn_Schnittebox.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_Schnittebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SchnitteboxActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_Schnittebox);

        btn_WartenAufAuftrag.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_WartenAufAuftrag.setText("<html><center>91. Warten auf Auftrag</center></html>");
        btn_WartenAufAuftrag.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_WartenAufAuftrag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WartenAufAuftragActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_WartenAufAuftrag);

        btn_Demontage.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Demontage.setText("<html><center>3. Demontage</center></html>");
        btn_Demontage.setAlignmentY(0.0F);
        btn_Demontage.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_Demontage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemontageActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_Demontage);

        btn_EinAuslagerungWerkzeugKomponente.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_EinAuslagerungWerkzeugKomponente.setText("<html><center>41. Ein- / Auslagerung:<br> Werkzeug / Komponente</center></html>");
        btn_EinAuslagerungWerkzeugKomponente.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_EinAuslagerungWerkzeugKomponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EinAuslagerungWerkzeugKomponenteActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_EinAuslagerungWerkzeugKomponente);

        btn_WartenAufWerkzeugAusDerProduktion1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_WartenAufWerkzeugAusDerProduktion1.setText("<html><center>92. Warten auf Werkzeug<br>(aus der Produktion)</center></html>");
        btn_WartenAufWerkzeugAusDerProduktion1.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_WartenAufWerkzeugAusDerProduktion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_WartenAufWerkzeugAusDerProduktion1ActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_WartenAufWerkzeugAusDerProduktion1);

        btn_MontageSTAL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_MontageSTAL.setText("<html><center>4. Montage: STAL</center></html>");
        btn_MontageSTAL.setAlignmentY(0.0F);
        btn_MontageSTAL.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_MontageSTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MontageSTALActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_MontageSTAL);

        btn_EinlagerungSchnitt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_EinlagerungSchnitt.setText("<html><center>42. Einlagerung:<br> Schnitt</center></html>");
        btn_EinlagerungSchnitt.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_EinlagerungSchnitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EinlagerungSchnittActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_EinlagerungSchnitt);

        btn_BesprechungVersammlung.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_BesprechungVersammlung.setText("<html><center>93. Besprechung / Versammlung</center></html>");
        btn_BesprechungVersammlung.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_BesprechungVersammlung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BesprechungVersammlungActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_BesprechungVersammlung);

        btn_DemontageSTAL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_DemontageSTAL.setText("<html><center>5. Demontage: STAL</center></html>");
        btn_DemontageSTAL.setAlignmentY(0.0F);
        btn_DemontageSTAL.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_DemontageSTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DemontageSTALActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_DemontageSTAL);

        btn_SucheWerkzeugKomponente.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_SucheWerkzeugKomponente.setText("<html><center>43. Suche:<br> Werkzeug / Komponente</center></html>");
        btn_SucheWerkzeugKomponente.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_SucheWerkzeugKomponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SucheWerkzeugKomponenteActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_SucheWerkzeugKomponente);

        btn_Schulung.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Schulung.setText("<html><center>96. Schulung</center></html>");
        btn_Schulung.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_Schulung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SchulungActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_Schulung);

        btn_ReparaturFormstation.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_ReparaturFormstation.setText("<html><center>10. Reparatur:<br> Formstation</center></html>");
        btn_ReparaturFormstation.setAlignmentY(0.0F);
        btn_ReparaturFormstation.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_ReparaturFormstation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReparaturFormstationActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_ReparaturFormstation);

        btn_PutzenReinigung.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_PutzenReinigung.setText("<html><center>60. Putzen / Reinigung</center></html>");
        btn_PutzenReinigung.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_PutzenReinigung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PutzenReinigungActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_PutzenReinigung);

        btn_Pause.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Pause.setText("<html><center>98. Pause</center></html>");
        btn_Pause.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PauseActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_Pause);

        btn_ReparaturStapelung.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_ReparaturStapelung.setText("<html><center>11. Reparatur:<br> Stapelung</center></html>");
        btn_ReparaturStapelung.setAlignmentY(0.0F);
        btn_ReparaturStapelung.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_ReparaturStapelung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReparaturStapelungActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_ReparaturStapelung);

        btn_Segmentwechsel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_Segmentwechsel.setText("<html><center>71. Segmentwechsel</center></html>");
        btn_Segmentwechsel.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_Segmentwechsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SegmentwechselActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_Segmentwechsel);

        btn_KeineMitarbeiter.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn_KeineMitarbeiter.setText("<html><center>99. Keine Mitarbeiter</center></html>");
        btn_KeineMitarbeiter.setPreferredSize(new java.awt.Dimension(300, 60));
        btn_KeineMitarbeiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KeineMitarbeiterActionPerformed(evt);
            }
        });
        jPanel_base.add(btn_KeineMitarbeiter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_base, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_base, javax.swing.GroupLayout.DEFAULT_SIZE, 1415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VorbereitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VorbereitungActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "1. Vorbereitung";
        dispose();
    }//GEN-LAST:event_btn_VorbereitungActionPerformed

    private void btn_NacharbeitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NacharbeitActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "2. Nacharbeit";
        dispose();
    }//GEN-LAST:event_btn_NacharbeitActionPerformed

    private void btn_DemontageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemontageActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "3. Demontage";
        dispose();
    }//GEN-LAST:event_btn_DemontageActionPerformed

    private void btn_MontageSTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MontageSTALActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "4. Montage: STAL";
        dispose();
    }//GEN-LAST:event_btn_MontageSTALActionPerformed

    private void btn_DemontageSTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DemontageSTALActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "5. Demontage: STAL";
        dispose();
    }//GEN-LAST:event_btn_DemontageSTALActionPerformed

    private void btn_ReparaturFormstationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReparaturFormstationActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "10. Reparatur: Formstation";
        dispose();
    }//GEN-LAST:event_btn_ReparaturFormstationActionPerformed

    private void btn_ReparaturStapelungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReparaturStapelungActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "11. Reparatur: Stapelung";
        dispose();
    }//GEN-LAST:event_btn_ReparaturStapelungActionPerformed

    private void btn_ReparaturSchnittStanzbrilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReparaturSchnittStanzbrilleActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "12. Reparatur: Schnitt / Stanzbrille";
        dispose();
    }//GEN-LAST:event_btn_ReparaturSchnittStanzbrilleActionPerformed

    private void btn_SchnitteboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SchnitteboxActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "40. Schnittebox";
        dispose();
    }//GEN-LAST:event_btn_SchnitteboxActionPerformed

    private void btn_EinAuslagerungWerkzeugKomponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EinAuslagerungWerkzeugKomponenteActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "41. Ein- / Auslagerung: Werkzeug / Komponente";
        dispose();
    }//GEN-LAST:event_btn_EinAuslagerungWerkzeugKomponenteActionPerformed

    private void btn_EinlagerungSchnittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EinlagerungSchnittActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "42. Einlagerung: Schnitt";
        dispose();
    }//GEN-LAST:event_btn_EinlagerungSchnittActionPerformed

    private void btn_SucheWerkzeugKomponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SucheWerkzeugKomponenteActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "43. Suche: Werkzeug / Komponente";
        dispose();
    }//GEN-LAST:event_btn_SucheWerkzeugKomponenteActionPerformed

    private void btn_PutzenReinigungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PutzenReinigungActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "60. Putzen / Reinigung";
        dispose();
    }//GEN-LAST:event_btn_PutzenReinigungActionPerformed

    private void btn_SegmentwechselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SegmentwechselActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "71. Segmentwechsel";
        dispose();
    }//GEN-LAST:event_btn_SegmentwechselActionPerformed

    private void btn_SchichtuebergabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SchichtuebergabeActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "80. Schichtübergabe";
        dispose();
    }//GEN-LAST:event_btn_SchichtuebergabeActionPerformed

    private void btn_WartenAufAuftragActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WartenAufAuftragActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "91. Warten auf Auftrag";
        dispose();
    }//GEN-LAST:event_btn_WartenAufAuftragActionPerformed

    private void btn_WartenAufWerkzeugAusDerProduktion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_WartenAufWerkzeugAusDerProduktion1ActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "92. Warten auf Werkzeug (aus der Produktion)";
        dispose();
    }//GEN-LAST:event_btn_WartenAufWerkzeugAusDerProduktion1ActionPerformed

    private void btn_BesprechungVersammlungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BesprechungVersammlungActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "93. Besprechung / Versammlung";
        dispose();
    }//GEN-LAST:event_btn_BesprechungVersammlungActionPerformed

    private void btn_SchulungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SchulungActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "96. Schulung";
        dispose();
    }//GEN-LAST:event_btn_SchulungActionPerformed

    private void btn_PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PauseActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "98. Pause";
        dispose();
    }//GEN-LAST:event_btn_PauseActionPerformed

    private void btn_KeineMitarbeiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KeineMitarbeiterActionPerformed
        // TODO add your handling code here:
        Taetigkeit = "99. Keine Mitarbeiter";
        dispose();
    }//GEN-LAST:event_btn_KeineMitarbeiterActionPerformed

    public String getTaetigkeit() {
        return Taetigkeit;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDE_TaetigkeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDE_TaetigkeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDE_TaetigkeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDE_TaetigkeitenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            BDE_TaetigkeitenDialog dialog = new BDE_TaetigkeitenDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BesprechungVersammlung;
    private javax.swing.JButton btn_Demontage;
    private javax.swing.JButton btn_DemontageSTAL;
    private javax.swing.JButton btn_EinAuslagerungWerkzeugKomponente;
    private javax.swing.JButton btn_EinlagerungSchnitt;
    private javax.swing.JButton btn_KeineMitarbeiter;
    private javax.swing.JButton btn_MontageSTAL;
    private javax.swing.JButton btn_Nacharbeit;
    private javax.swing.JButton btn_Pause;
    private javax.swing.JButton btn_PutzenReinigung;
    private javax.swing.JButton btn_ReparaturFormstation;
    private javax.swing.JButton btn_ReparaturSchnittStanzbrille;
    private javax.swing.JButton btn_ReparaturStapelung;
    private javax.swing.JButton btn_Schichtuebergabe;
    private javax.swing.JButton btn_Schnittebox;
    private javax.swing.JButton btn_Schulung;
    private javax.swing.JButton btn_Segmentwechsel;
    private javax.swing.JButton btn_SucheWerkzeugKomponente;
    private javax.swing.JButton btn_Vorbereitung;
    private javax.swing.JButton btn_WartenAufAuftrag;
    private javax.swing.JButton btn_WartenAufWerkzeugAusDerProduktion1;
    private javax.swing.JPanel jPanel_base;
    // End of variables declaration//GEN-END:variables
}
